### ISSUE TITLE
一部の手牌でシャンテン数が誤計算される

### ISSUE THREAD

**Issue by Apricot-S** [paithiov909/shikakusphere#1]
以下のような手牌でシャンテン数が誤計算されます。

```R
library("shikakusphere")

hands <- c(
  "p1111234444s999s9",  # 1 シャンテン
  "z1111222233344z4",   # 1 シャンテン
  "s123456789z1111"     # 1 シャンテン
)

n_xiangting <- calc_xiangting(hands)
n_xiangting
#> [1] 0 0 0
```

参考までに天鳳牌理 (https://tenhou.net/2/) ではそれぞれ以下のようになります。
- p1111234444s999s9
![1111234444p9999s](https://github.com/user-attachments/assets/83baae1e-0701-49a8-9f97-e772bb6e69e3)
- z1111222233344z4
![11112222333444z](https://github.com/user-attachments/assets/789c6977-9505-44dd-b40b-7045b0ee3f91)
- s123456789z1111
(天鳳牌理の仕様上ツモ牌を追加していますが、中を切った場合は聴牌になりません)
![123456789s1111z7z](https://github.com/user-attachments/assets/c0ad26cd-ba0a-47b7-b585-a237954a19e2)

**Comment by paithiov909** [comment]
報告されたケースについては 6aeb6f55443e28705daf424568b6e853948a24ac で、さしあたり修正できたと思います。また、そもそもテストを書いていなかったので、cmajiangのテストケースを参考にテストを追加しました。

クローズするかは、もうすこしテストケースを増やしてみながら判断します。ただ、現段階ではcmajiangのC++ソースを積極的に変更していくことはあまり考えていないため、cmajiang側の実装の修正については、優先度が低いかもしれないです。

**Comment by Apricot-S** [comment]
早速のご対応ありがとうございます。

テストケースの

https://github.com/paithiov909/shikakusphere/blob/2fe12b06384e73341df83066a091755a6285b4fc/tests/testthat/test-xiangting.R#L30

ですが、13 枚のこちらも 1 シャンテンとするのが一般的かと思います。
参考までに二次箱牌理ツール (https://hako2d-mj.xii.jp/mahjong_tool/soul.html) の結果を添付します。
![スクリーンショット 2024-10-19 171302](https://github.com/user-attachments/assets/ee81c9bc-83c8-47cf-b24c-eee11542c5b4)

**Comment by Apricot-S** [comment]
> クローズするかは、もうすこしテストケースを増やしてみながら判断します。ただ、現段階ではcmajiangのC++ソースを積極的に変更していくことはあまり考えていないため、cmajiang側の実装の修正については、優先度が低いかもしれないです。

cmajiang のラッパーである本リポジトリより、cmajiang または cmajiang の移植元である majiang-core に報告すべきだったかもしれません。失礼しました。

また、majiang-core の作者は以下のように言っているので、5 枚目の待ちを許容するのは仕様とするのも有りかもしれません。
https://x.com/koba0367/status/1825698229083844629
> 電脳麻将のライブラリでは、Majiang.Util.xiangting()が0(テンパイ)を返し、Majiang.Util.tingpai()が空配列(論理上の有効牌なし)を返す設計になってる。

シャンテン数計算ライブラリ単体として見ると誤計算していますが、立直や荒牌平局の際は有効牌の有無をチェックするので麻雀ゲームの実装全体としては問題ないという判断かもしれません。
cmajiang も dlmahjong の強化学習用のシミュレーターとして作成されたようなので、この点を問題としていないのかもしれません。

本問題は shikakusphere の用途で修正要否が変わる問題と思われます。
どのような用途を想定されていますか?

たとえば、ランダムに手牌を生成してシャンテン数分布の統計データを取るというような用途も想定されているのであれば、誤計算は修正した方がよいと思われます。

**Comment by paithiov909** [comment]
ありがとうございます。とりあえず、`p1111234444s999`のテストケースについて、1シャンテンと返されるように修正しました。

1. p1111234444s999s9
2. z1111222233344z4
3. s123456789z1111

挙げてもらったこれらのケースのうち、2と3については[このあたり](https://github.com/paithiov909/shikakusphere/blob/2fe12b06384e73341df83066a091755a6285b4fc/src/xiangting.cpp#L124-L136)を修正すればよさそうだったのですが、1については、率直にいって、適当な修正ができているのかよくわかっていません。かえっておかしな計算になっているような気もします。

このRパッケージでどんな用途を想定しているかという質問にも関連しますが、いまのところ「とりあえずラッパーを書きながら試しに触ってみている」ような段階なので、いずれにせよ、もうすこし時間をかけて挙動を確認したいと思っています。誤計算の対応を含め、このパッケージとしてどんな機能をどこまで実現するか決めるには、まだcmajiangについて理解できていない点が多すぎます。

> たとえば、ランダムに手牌を生成してシャンテン数分布の統計データを取るというような用途も想定されているのであれば、誤計算は修正した方がよいと思われます

やるかはわからないですが、そういう使い方ができれば便利かなとは思います。手牌をランダムに生成する機能はほしいですね。cmajiangが念頭においていそうなGameクラスのインスタンスをもって対局をシミュレートできるみたいな機能は、R言語の書き方に馴染まないですし、たぶん実装しないです。

**Comment by paithiov909** [comment]
[patrick](https://github.com/google/patrick)によるparameterized testを追加しました。[cmajiang/tests_cpp/xiangting_test.cpp](https://github.com/TadaoYamaoka/cmajiang/blob/main/tests_cpp/xiangting_test.cpp)でテストされているケースから4,000件だけ抽出してテストケースとしたところ、次のようなケースでシャンテン数の計算が間違っているらしいことがわかりました。

- `m12344556666789`
- `m23456666777889`
- `m12345667788889`

ここでは4,000件だけ抽出しているので、実際にはもっと多くのケースで間違っているようです。

```r
══ Results ═══════════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 25.1 s

── Failed tests ──────────────────────────────────────────────────────────────────────────────────────────────────────
Failure (test-patrick-xiangting.R:7:5): calc_xiangting works q=m12344556666789, x=-1, 11, 3, n=-1
calc_xiangting(q) (`actual`) not equal to `n` (`expected`).

  `actual`:  0
`expected`: -1
Backtrace:
    ▆
 1. ├─rlang::eval_tidy(code, args)
 2. └─testthat::expect_equal(calc_xiangting(q), n) at test-patrick-xiangting.R:7:5

Failure (test-patrick-xiangting.R:7:5): calc_xiangting works q=m23456666777889, x=-1, 12, 3, n=-1
calc_xiangting(q) (`actual`) not equal to `n` (`expected`).

  `actual`:  0
`expected`: -1
Backtrace:
    ▆
 1. ├─rlang::eval_tidy(code, args)
 2. └─testthat::expect_equal(calc_xiangting(q), n) at test-patrick-xiangting.R:7:5

Failure (test-patrick-xiangting.R:7:5): calc_xiangting works q=m12345667788889, x=-1, 11, 3, n=-1
calc_xiangting(q) (`actual`) not equal to `n` (`expected`).

  `actual`:  0
`expected`: -1
Backtrace:
    ▆
 1. ├─rlang::eval_tidy(code, args)
 2. └─testthat::expect_equal(calc_xiangting(q), n) at test-patrick-xiangting.R:7:5

[ FAIL 3 | WARN 0 | SKIP 0 | PASS 4037 ]
```

**Comment by paithiov909** [comment]
C++側でのシャンテン数の計算部分について[shanten-number](https://github.com/tomohxx/shanten-number)の実装に置き換えました。新たに追加したものを含むすべてのテストケースについて、シャンテン数の計算は間違えないことを確認しました。

ただし、この実装は「純手牌を和了形（聴牌形）に変形するのに必要な最小ツモ数」を返すため、`m1134`のような少牌に対して返される結果が従来のcmajiangにおける実装とは異なっています。また、`collect_tingpai()`についても、内部で同じ関数を利用するため、従来のものとは返される結果が異なります。

一方で、とくに`collect_tingpai()`の結果としてはshanten-numberを使用した後のほうがかえって自然に思われるため、このパッケージではこれが正しいということにします。

#### cmajiangをそのまま使用

```r
library(shikakusphere)
calc_xiangting("m1134")
#> [1] 9
collect_tingpai("m1134")
#> [[1]]
#> [1] "m1" "m2" "m3" "m4" "m5" "m6" "m7" "m8" "m9" "p1" "p2" "p3" "p4" "p5" "p6" "p7"
#> [17] "p8" "p9" "s1" "s2" "s3" "s4" "s5" "s6" "s7" "s8" "s9" "z1" "z2" "z3" "z4" "z5"
#> [33] "z6" "z7"
```

#### shanten-numberを使用

``` r
library(shikakusphere)
calc_xiangting("m1134")
#> # A tibble: 1 × 2
#>     num mode 
#>   <int> <fct>
#> 1     0 yiban
collect_tingpai("m1134")
#> [[1]]
#> [1] "m2" "m5"
```

<sup>Created on 2024-11-03 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

なお、「5枚目の待ち牌を許容するか」については、cmajiangでは純手牌中に4枚あるときに有効牌として返さないようにしていたため、同様の挙動にしています。

https://github.com/paithiov909/shikakusphere/blob/771e9a332bce39a2021f7971968e77c998cae8cb/tests/testthat/test-tingpai.R#L23-L32
